import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react'
import styles from '../styles/Home.module.css'
import Game from '../e/Game'
import AI from '../e/AI'
import Script from 'next/script'

function Cell(props) {
  return (
    <div className="box" id={props.id} onClick={()=>props.onclick()}>{props.value}</div>
  )
}

export default function Home() {
  const [game, setGame] = useState(new Game())
  const [board, setBoard] = useState(game.currentState.board.map((e)=>e=="E"?"":e))
  const [AIplayer, setAIplayer] = useState(new AI(game))
  const [text, setText] = useState("")
         
  var aiptag = aiptag || {};
  aiptag.cmd = aiptag.cmd || [];
  aiptag.cmd.display = aiptag.cmd.display || [];
  aiptag.cmd.player = aiptag.cmd.player || [];

  //CMP tool settings
  aiptag.cmp = {
    show: true,
    position: "centered",  //centered or bottom
    button: true,
    buttonText: "Privacy settings",
    buttonPosition: "bottom-left" //bottom-left, bottom-right, top-left, top-right
  }
  return (

    
    <div className={styles.container}>
      <Script src="//api.adinplay.com/libs/aiptag/pub/SWT/swordbattle.io/tag.min.js"></Script>
      <Head>


  
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main>
      <h1>{text}</h1>

    <button onClick={
    () => {
      location.reload()
    }
    }>Retry</button>
  <br/>
  <br/>
    <div className="game-board">

    {[0,1,2,3,4,5,6,7,8].map((e) => {
      return (<Cell id={e} key={e} value={board[e]} onclick={() => {
              if(game.currentState.ended())  return;
      
        if(game.currentState.board[e] != "E") return;
        
      game.placeNext(e)
        if(game.currentState.ended())  setText(game.currentState.result)
       else AIplayer.play();
        
            if(game.currentState.ended()) setText(game.currentState.result)
           setBoard([...game.currentState.board].map((e)=>e=="E"?"":e))
    return true
      }}/>)
    })}
    
</div>
    </main>

    </div>
  )
}
